# Generated by Django 4.1.4 on 2023-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mounth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
