# Generated by Django 4.1.4 on 2023-04-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_mounth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mounth',
        ),
    ]
