# Generated by Django 4.1.6 on 2023-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_user_alter_application_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='client_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='client_number',
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
