# Generated by Django 4.1.6 on 2023-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_student_student_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
