# Generated by Django 4.1.4 on 2023-04-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_students5_course_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
