# Generated by Django 4.1.4 on 2023-04-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
