# Generated by Django 4.1.4 on 2023-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
