# Generated by Django 4.1.4 on 2023-04-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_teacher_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
    ]
