# Generated by Django 4.1.4 on 2023-04-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_remove_course_students_remove_course_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='userr',
        ),
    ]
