# Generated by Django 4.1.4 on 2023-04-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_rename_user_review_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='userr',
            new_name='user',
        ),
    ]
