# Generated by Django 4.1.4 on 2023-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_rename_userr_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, related_name='course_students', to='course.student'),
        ),
    ]
