# Generated by Django 4.1.4 on 2023-04-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_selectedperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedPerson',
        ),
    ]
