# Generated by Django 4.1.4 on 2023-04-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_delete_selectedperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, related_name='course_students', to='course.student'),
        ),
    ]
